<div id="sharepage">
    <div class="title"><a rel="nofollow" href="http://blog.sjinks.org.ua/php/wordpress/202-onebutton-better-version-of-odnaknopka/"><?php _e("Add to Social Bookmarks", "onebutton"); ?></a></div>
    <ul class="clearfix">
        <!-- BLINK --><li id="blink" title="<?php _e("Add to Blink", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.blinklist.com/index.php?Action=Blink/addblink.php&amp;url={url}&amp;title={title}&amp;description={description}"><?php _e("Blink", "onebutton"); ?></a></li><!-- /BLINK -->
        <!-- DELICIOUS --><li id="delicious" title="<?php _e("Add to del.ici.ous", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://del.icio.us/post?url={url}&amp;title={title}"><?php _e("del.ici.ous", "onebutton"); ?></a></li><!-- /DELICIOUS -->
        <!-- DIGG --><li id="digg" title="<?php _e("Add to Digg", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://digg.com/submit?phase=2&amp;url={url}"><?php _e("Digg", "onebutton"); ?></a></li><!-- /DIGG -->
        <!-- FURL --><li id="furl" title="<?php _e("Add to Furl", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.furl.net/storeIt.jsp?u={url}&amp;t={title}"><?php _e("Furl", "onebutton"); ?></a></li><!-- /FURL -->
        <!-- GOOGLE --><li id="google" title="<?php _e("Add to Google", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://fusion.google.com/add?feedurl={url}"><?php _e("Google", "onebutton"); ?></a></li><!-- /GOOGLE -->
        <!-- SIMPY --><li id="simpy" title="<?php _e("Add to Simpy", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://simpy.com/simpy/LinkAdd.do?href=&amp;title={title}&amp;note={description}&amp;_doneURI={url}&amp;v=6&amp;src=bookmarklet"><?php _e("Simpy", "onebutton"); ?></a></li><!-- /SIMPY -->
        <!-- SPURL --><li id="spurl" title="<?php _e("Add to Spurl", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.spurl.net/spurl.php?v=3&amp;url={url}&amp;title={title}&amp;blocked={description}"><?php _e("Spurl", "onebutton"); ?></a></li><!-- /SPURL -->
        <!-- YMYWEB --><li id="ymyweb" title="<?php _e("Add to Y! MyWeb", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://myweb2.search.yahoo.com/myresults/bookmarklet?u={url}&amp;t={title}&amp;d=&amp;ei=UTF-8"><?php _e("Y! MyWeb", "onebutton"); ?></a></li><!-- /YMYWEB -->
        <!-- BOBRDOBR --><li id="bobrdobr" title="<?php _e("Add to BobrDobr", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://bobrdobr.ru/addext.html?url={url}&amp;title={title}"><?php _e("BobrDobr", "onebutton"); ?></a></li><!-- /BOBRDOBR -->
        <!-- MRWONG --><li id="mrwong" title="<?php _e("Add to Mister Wong", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.mister-wong.ru/index.php?action=addurl&amp;bm_url={url}&amp;bm_description={title}"><?php _e("Mr. Wong", "onebutton"); ?></a></li><!-- /MRWONG -->
        <!-- YABM --><li id="yabm" title="<?php _e("Add to Yandex.Bookmarks", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://zakladki.yandex.ru/userarea/links/addfromfav.asp?bAddLink_x=1&amp;lurl={url}&amp;lname={title}"><?php _e("Yandex.Bookmarks", "onebutton"); ?></a></li><!-- /YABM -->
        <!-- TEXT20 --><li id="text20" title="<?php _e("Add to Text 2.0", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://text20.ru/add/?source={url}&amp;title={title}&amp;text={description}"><?php _e("Text 2.0", "onebutton"); ?></a></li><!-- /TEXT20 -->
        <!-- NEWS2 --><li id="news2" title="<?php _e("Add to News2", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://news2.ru/add_story.php?url={url}"><?php _e("News2", "onebutton"); ?></a></li><!-- /NEWS2 -->
        <!-- ADDSCOOP --><li id="addscoop" title="<?php _e("Add to AddScoop", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://myscoop.ru/add/?URL={url}&amp;title={title}"><?php _e("AddScoop", "onebutton"); ?></a></li><!-- /ADDSCOOP -->
        <!-- RUSPACE --><li id="ruspace" title="<?php _e("Add to RuSpace", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.ruspace.ru/index.php?link=bookmark&amp;action=bookmarkNew&amp;bm=1&amp;url={url}&amp;title={title}"><?php _e("RuSpace", "onebutton"); ?></a></li><!-- /RUSPACE -->
        <!-- RUMARKZ --><li id="rumarkz" title="<?php _e("Add to RUmarkz", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://rumarkz.ru/bookmarks/?action=add&amp;popup=1&amp;address={url}&amp;title={title}"><?php _e("RUmarkz", "onebutton"); ?></a></li><!-- /RUMARKZ -->
        <!-- MEMORI --><li id="memori" title="<?php _e("Add to Memori", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://memori.ru/link/?sm=1&amp;u_data[url]={url}&amp;u_data[name]={title}"><?php _e("Memori", "onebutton"); ?></a></li><!-- /MEMORI -->
        <!-- GOOGLEBM --><li id="googlebm" title="<?php _e("Add to Google Bookmarks", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.google.com/bookmarks/mark?op=add&amp;bkmk={url}&amp;title={title}"><?php _e("Google Bookmarks", "onebutton"); ?></a></li><!-- /GOOGLEBM -->
        <!-- PISALI --><li id="pisali" title="<?php _e("Add to Pisali", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://pisali.ru/load_article/"><?php _e("Pisali", "onebutton"); ?></a></li><!-- /PISALI -->
        <!-- SMI2 --><li id="smi2" title="<?php _e("Add to SMI 2", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://smi2.ru/add/"><?php _e("SMI 2", "onebutton"); ?></a></li><!-- /SMI2 -->
        <!-- MYPLACE --><li id="myplace" title="<?php _e("Add to Moe Mesto", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://moemesto.ru/post.php?url={url}&amp;title={title}"><?php _e("Moe Mesto", "onebutton"); ?></a></li><!-- /MYPLACE -->
        <!-- BM100 --><li id="bm100" title="<?php _e("Add to Sto Zakladok", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.100zakladok.ru/save/?bmurl={url}&amp;bmtitle={title}"><?php _e("100 Zakladok", "onebutton"); ?></a></li><!-- /BM100 -->
        <!-- WOW --><li id="wow" title="<?php _e("Add to Vaau!", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.vaau.ru/submit/?action=step2&amp;url={url}"><?php _e("Vaau!", "onebutton"); ?></a></li><!-- /WOW -->
        <!-- TECHNORATI --><li id="technorati" title="<?php _e("Add to Technorati", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://technorati.com/faves?add={url}"><?php _e("Technorati", "onebutton"); ?></a></li><!-- /TECHNORATI -->
        <!-- RUCITY --><li id="rucity" title="<?php _e("Add to RuCity", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://rucity.com/bookmarks.php?action=add&amp;address={url}&amp;title={title}&amp;description={description}"><?php _e("RuCity", "onebutton"); ?></a></li><!-- /RUCITY -->
        <!-- LINKSTORE --><li id="linkstore" title="<?php _e("Add to LinkStore", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://linkstore.ru/servlet/LinkStore?a=add&amp;url={url}&amp;title={title}"><?php _e("LinkStore", "onebutton"); ?></a></li><!-- /LINKSTORE -->
        <!-- NEWSLAND --><li id="newsland" title="<?php _e("Add to NewsLand", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://newsland.ru/News/Add/type/news/"><?php _e("NewsLand", "onebutton"); ?></a></li><!-- /NEWSLAND -->
        <!-- LOPAS --><li id="lopas" title="<?php _e("Add to Lopas", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.lopas.ru/add_story.php?story_url={url}"><?php _e("Lopas", "onebutton"); ?></a></li><!-- /LOPAS -->
        <!-- LIUA --><li id="liua" title="<?php _e("Add to Bookmarks - I.UA", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://links.i.ua/add/?url={url}&amp;name={title}&amp;text={description}&amp;labels={tags}"><?php _e("Закладки - I.UA", "onebutton"); ?></a></li><!-- /LIUA -->
        <!-- CONNOTEA --><li id="connotea" title="<?php _e("Add to Connotea", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.connotea.org/add?uri={url}&amp;usertitle={title}&amp;tags={tags}&amp;description={description}"><?php _e("Connotea", "onebutton"); ?></a></li><!-- /CONNOTEA -->
        <!-- BIBSONOMY --><li id="bibsonomy" title="<?php _e("Add to Bibsonomy", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://www.bibsonomy.org/ShowBookmarkEntry?c=b&amp;jump=yes&amp;url={url}&amp;description={title}&amp;extended={description}"><?php _e("Bibsonomy", "onebutton"); ?></a></li><!-- /BIBSONOMY -->
        <!-- TRUCKING --><li id="trucking" title="<?php _e("Add to Trucking Bookmarks", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://macke1.com/bookmarks.php/?action=add&amp;address={url}&amp;title={title}&amp;description={description}&amp;tags={tags}"><?php _e("Trucking Bookmarks", "onebutton"); ?></a></li><!-- /TRUCKING -->
        <!-- COMMUNIZM --><li id="communizm" title="<?php _e("Add to Communizm", "onebutton") ?>"><a rel="external{nofollow}"{target} href="http://communizm.ru/index.php?mode=addstory&amp;title={title}&amp;link={url}"><?php _e("Communizm", "onebutton"); ?></a></li><!-- /COMMUNIZM -->
        <!-- UCA --><li id="uca" title="<?php _e("Add to UCA", "onebutton"); ?>"><a rel="external{nofollow}"{target} href="http://uca.kiev.ua/bookmarks.php/?action=add&amp;address={url}&amp;title={title}&amp;description={description}&amp;tags={tags}"><?php _e("UCA", "onebutton"); ?></a></li>
    </ul>
</div>
